name: Glitch Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    environment:
      name: glitch
      url: https://reverse-geocode-superface.glitch.me
    steps:
    - name: Sync to Glitch Project
      uses: kanadgupta/glitch-sync@v1.1
      with:
        project-id: '${{ secrets.PROJECT_ID }}'
        auth-token: '${{ secrets.AUTH_TOKEN }}'
